apiVersion: apps/v1
kind: Deployment
metadata:
  name: aksdemo
spec:
  selector:
    matchLabels:
      app: aksdemo
  template:
    metadata:
      labels:
        app: aksdemo
    spec:
      containers:
      - name: aksdemo
        image: myclustacr.azurecr.io/myclust4c62:1
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
