apiVersion : apps/v1
kind: Deployment
metadata:
  name: aksdemo 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: aksdemo 
    spec:
      containers:
        - name: aksdemo 
          image: myclustacr.azurecr.io/myclust4c62:1 
          imagePullPolicy: Always
          ports:
          - containerPort: 80
